---
- name: Install fish
  become: true
  package:
    name: fish
    state: installed

- name: Create fish config directory
  file:
    path: "~/.config/fish"
    state: directory

- name: Symlink fish config file
  file:
    src: "{{ role_path }}/files/config.fish"
    dest: "~/.config/fish/config.fish"
    state: link
