---
- include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"

- name: Install network debugging tools
  become: True
  package:
    name: "{{ item }}"
  with_items:
    - ipcalc
    - mtr
    - traceroute
    - whois
    - "{{ bind_tools_package_name }}"  # dig, nslookup
    - "{{ ldns_package_name }}"  # drill
    - iperf
